export const authActions = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  SET_PASSWORD: "SET_PASSWORD",
} as const;

export const userActions = {
  GET_USERS: "GET_USERS",
  GET_USER_DETAILS: "GET_USER_DETAILS",
  UPDATE_USER: "UPDATE_USER",
  ADD_USER: "ADD_USER",
} as const;

export const dropdownActions = {
  GET_DROPDOWN: "GET_DROPDOWN",
} as const;

export const leadActions = {
  CREATE_LEAD: "CREATE_LEAD",
  GET_LEADS: "GET_LEADS",
  GET_LEAD_DETAILS: "GET_LEAD_DETAILS",
  UPDATE_LEAD_STATUS: "UPDATE_LEAD_STATUS",
  UPDATE_LEAD: "UPDATE_LEAD",
} as const;

export const crmActions = {
  GET_CRM_ANALYTICS: "GET_CRM_ANALYTICS",
};

export const admissionActions = {
  SUBMIT_ADMISSION: "SUBMIT_ADMISSION",
  GET_ADMISSIONS: "GET_ADMISSIONS",
  GET_ADMISSION_DETAIL: "GET_ADMISSION_DETAIL",
  APPROVE_ADMISSION: "APPROVE_ADMISSION",
  REJECT_ADMISSION: "REJECT_ADMISSION",
  UPLOAD_PAYMENT: "UPLOAD_PAYMENT",
} as const;

export const studentActions = {
  GET_STUDENTS: "GET_STUDENTS",
  GET_STUDENT_DETAIL: "GET_STUDENT_DETAIL",
} as const;

export const settingActions = {
  GET_SETTINGS: "GET_SETTINGS",
  UPDATE_SETTINGS: "UPDATE_SETTINGS",
} as const;

export const branchAction = {
  GET_BRANCH: "GET_BRANCH",
  GET_BRANCH_STUDENTS: "GET_BRANCH_STUDENTS",
  UPDATE_BRANCH: "UPDATE_BRANCH",
  DELETE_BRANCH: "DELETE_BRANCH",
  CREATE_BRANCH: "CREATE_BRANCH",
} as const;

export const courseAction = {
  GET_COURSES: "GET_COURSES",
  GET_COURSE_DETAILS: "GET_COURSE_DETAILS",
  CREATE_COURSE: "CREATE_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
} as const;

export const batchAction = {
  GET_BATCHES: "GET_BATCHES",
  GET_BATCH_DETAILS: "GET_BATCH_DETAILS",
  CREATE_BATCH: "CREATE_BATCH",
  UPDATE_BATCH: "UPDATE_BATCH",
  DELETE_BATCH: "DELETE_BATCH",
  ASSIGN_STUDENT: "ASSIGN_STUDENT",
  REMOVE_STUDENT: "REMOVE_STUDENT",
  ASSIGN_FACULTY: "ASSIGN_FACULTY",
  REMOVE_FACULTY: "REMOVE_FACULTY",
} as const;

export const subjectAction = {
  GET_SUBJECTS: "GET_SUBJECTS",
  CREATE_SUBJECT: "CREATE_SUBJECT",
  UPDATE_SUBJECT: "UPDATE_SUBJECT",
  DELETE_SUBJECT: "DELETE_SUBJECT",
} as const;

export const ChatAction = {
  GET_CHAT_ROOMS: "GET_CHAT_ROOMS",
  GET_CHAT_ROOM_DETAILS: "GET_CHAT_ROOM_DETAILS",
  CREATE_GROUP_CHAT: "CREATE_GROUP_CHAT",
  CREATE_DIRECT_CHAT: "CREATE_DIRECT_CHAT",
  SEND_CHAT_MESSAGE: "SEND_CHAT_MESSAGE",
  GET_CHAT_MESSAGES: "GET_CHAT_MESSAGES",
  UPDATE_GROUP: "UPDATE_GROUP",
} as const;

export const ClassroomAction = {
  GET_CLASSROOMS: "GET_CLASSROOMS",
  CREATE_CLASSROOMS: "CREATE_CLASSROOMS",
  UPDATE_CLASSROOMS: "UPDATE_CLASSROOMS",
  DELETE_CLASSROOMS: "DELETE_CLASSROOMS",
} as const;

export const TimetableAction = {
  GET_TIMETABLE: "GET_TIMETABLE",
  GET_TIMETABLE_DETAIL: "GET_TIMETABLE_DETAIL",
  CREATE_TIMETABLE: "CREATE_TIMETABLE",
  UPDATE_TIMETABLE: "UPDATE_TIMETABLE",
  DELETE_TIMETABLE: "DELETE_TIMETABLE",
} as const;

export const feesActions = {
  GET_FEE_STRUCTURES: "GET_FEE_STRUCTURES",
  // CREATE_FEE_STRUCTURES: "CREATE_FEE_STRUCTURES",
  // UPDATE_FEE_STRUCTURES: "UPDATE_FEE_STRUCTURES",
  // DELETE_FEE_STRUCTURES: "DELETE_FEE_STRUCTURES",
} as const;

export const attendanceActions = {
  GET_ATTENDANCE: "GET_ATTENDANCE",
  GET_ATTENDANCE_REPORT: "GET_ATTENDANCE_REPORT",
} as const;

export const levelActions = {
  GET_LEVELS: "GET_LEVELS",
  GET_LEVEL_DETAILS: "GET_LEVEL_DETAILS",
  CREATE_LEVEL: "CREATE_LEVEL",
  UPDATE_LEVEL: "UPDATE_LEVEL",
  DELETE_LEVEL: "DELETE_LEVEL",
} as const;
