export const authActions = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  SET_PASSWORD: "SET_PASSWORD",
} as const;

export const userActions = {
  GET_USERS: "GET_USERS",
  GET_USER_DETAILS: "GET_USER_DETAILS",
  UPDATE_USER: "UPDATE_USER",
  ADD_USER: "ADD_USER",
} as const;

export const dropdownActions = {
  GET_DROPDOWN: "GET_DROPDOWN",
} as const;

export const leadActions = {
  CREATE_LEAD: "CREATE_LEAD",
  GET_LEADS: "GET_LEADS",
  GET_LEAD_DETAILS: "GET_LEAD_DETAILS",
  UPDATE_LEAD_STATUS: "UPDATE_LEAD_STATUS",
} as const;

export const crmActions = {
  GET_CRM_ANALYTICS: "GET_CRM_ANALYTICS",
}

export const admissionActions = {
  SUBMIT_ADMISSION: "SUBMIT_ADMISSION",
  GET_ADMISSIONS: "GET_ADMISSIONS",
  GET_ADMISSION_DETAIL: "GET_ADMISSION_DETAIL",
  APPROVE_ADMISSION: "APPROVE_ADMISSION",
  REJECT_ADMISSION: "REJECT_ADMISSION",
  UPLOAD_PAYMENT: "UPLOAD_PAYMENT",
} as const;

export const studentActions = {
  GET_STUDENTS: "GET_STUDENTS",
  GET_STUDENT_DETAIL: "GET_STUDENT_DETAIL",
} as const;

export const settingActions = {
  GET_SETTINGS: "GET_SETTINGS",
  UPDATE_SETTINGS: "UPDATE_SETTINGS",
} as const;

export const branchAction = {
  GET_BRANCH: "GET_BRANCH",
  GET_BRANCH_STUDENTS: "GET_BRANCH_STUDENTS",
  UPDATE_BRANCH: "UPDATE_BRANCH",
  DELETE_BRANCH: "DELETE_BRANCH",
  CREATE_BRANCH: "CREATE_BRANCH",
} as const;

export const courseAction = {
  GET_COURSES: "GET_COURSES",
  GET_COURSE_DETAILS: "GET_COURSE_DETAILS",
  CREATE_COURSE: "CREATE_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
} as const;

export const batchAction = {
  GET_BATCHES: "GET_BATCHES",
  GET_BATCH_DETAILS: "GET_BATCH_DETAILS",
  CREATE_BATCH: "CREATE_BATCH",
  UPDATE_BATCH: "UPDATE_BATCH",
  DELETE_BATCH: "DELETE_BATCH",
} as const;

export const subjectAction = {
  CREATE_SUBJECT: "CREATE_SUBJECT",
  UPDATE_SUBJECT: "UPDATE_SUBJECT",
  DELETE_SUBJECT: "DELETE_SUBJECT",
} as const;

export const ChatAction = {
  GET_CHAT_ROOMS: "GET_CHAT_ROOMS",
  CREATE_GROUP_CHAT: "CREATE_GROUP_CHAT",
  CREATE_DIRECT_CHAT: "CREATE_DIRECT_CHAT",
  SEND_CHAT_MESSAGE: "SEND_CHAT_MESSAGE",
  GET_CHAT_MESSAGES: "GET_CHAT_MESSAGES",
} as const;
