"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _users_table from './users-table.bones.json'

registerBones({
  "users-table": _users_table,
})
